# Generated by Django 3.0.4 on 2020-06-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
